spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///D:/Cursos/spring-boot/arquitectura-microservicios/ecommerce-clean-architecture/config-data
          clone-on-start: true
          default-label: main
server:
  port: 9000
