pluginManagement {
    repositories {
        //mavenLocal()
        gradlePluginPortal()
    }
}

buildCache {
    local {
        directory = new File(rootDir, 'build-cache')
    }
}

rootProject.name = 'InventoryService'

include ':app-service'
include ':model'
include ':usecase'
project(':app-service').projectDir = file('./applications/app-service')
project(':model').projectDir = file('./domain/model')
project(':usecase').projectDir = file('./domain/usecase')
include ':jpa-repository'
project(':jpa-repository').projectDir = file('./infrastructure/driven-adapters/jpa-repository')
include ':api-rest'
project(':api-rest').projectDir = file('./infrastructure/entry-points/api-rest')
include ':mq-listener'
project(':mq-listener').projectDir = file('./infrastructure/entry-points/mq-listener')
include ':inventory-configuracion'
project(':inventory-configuracion').projectDir = file('./infrastructure/driven-adapters/inventory-configuracion')
include ':mq-sender'
project(':mq-sender').projectDir = file('./infrastructure/driven-adapters/mq-sender')